server:
  port: 8003
spring:
  application:
    name: easytobuy-product
  datesource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///easytobuy_product?useSSL=false
    user: root
    password: 123456