server:
  port: 9527
spring:
  application:
    name: zuul-gateway
zuul:
  ignored-services: "*"
  prefix: "/services"
  routes: #路由的配置
    plat.serviceId: easytobuy-plat
    plat.path: /plat/**
    product.serviceId: easytobuy-product
    product.path: /product/**
    common.serviceId: easytobuy-common
    common.path: /common/**