server:
  port: 8003
spring:
  application:
    name: easytobuy-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easytobuy_product?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
mybatis-plus:
    type-aliases-package:cn.etb.easytobuy.domain,cn.etb.easytobuy.query
